version: '3'
services:
  goapps:
    container_name: golang_application
    image: surajmachamasi/go-action-app-now:v5
    volumes:
      - .:/opt/goapp
    ports:
      - 3200:8080
    restart: always






