name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-go-app:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
                 

    - name: Build
      run: |
       go get -v -d
       go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    - name: BUild and push-to-docker-hub
      uses: docker/build-push-action@v2
      with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: surajmachamasi/go-lang-custom:go-version
  deploy_nodeapp:
      needs: [build-go-app]
      runs-on: ubuntu-latest
      steps:
      - name: SSH and deploy go app to the Linux-VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          script: |
            sudo rm -r gah-node
            git clone https://github.com/sjnyos/gah-golang.git
            cd ~/gah-node
            docker-compose build
            docker-compose up -d

        




  